---
- name: verification de la connexion au client
  ping:
- name: Installation serveur MySQL
  apt:
    name: mysql-server
    state: present
- name: Installation du package python mysqldb
  apt:
    name: python-mysqldb
    state: present
- name: Autoriser les connexions distantes pour mysql
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify:
    - Restart MySQL
