---
- name: install curl, openssh-server, ca-certificates
  apt:
    name: ['curl','openssh-server','ca-certificates']
    state: latest

- name: install postfix
  apt:
    name: postfix
    state: latest

- name: Download GitLab repository installation script.
  get_url:
    url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
    dest: /tmp/gitlab_install_repository.sh
#  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
#  when: not gitlab_file.stat.exists

#- name: Define the Gitlab package name.
#  set_fact:
#    gitlab_package_name: "{{ gitlab_edition }}{{ gitlab_package_version_separator }}{{ gitlab_version }}"
#  when: gitlab_version != ''

- name: Install GitLab
  package:
    name: "gitlab-ce"
    state: present
#  when: not gitlab_file.stat.exists
